_target_: boltzgen.task.filter.filter.Filter
budget: 100
top_budget: 10
use_affinity: false
filter_cysteine: false
from_inverse_folded: true
filter_bindingsite: false
modality: peptide
peptide_type: linear
alpha: 0.001
random_state: 0
metrics_override: null
num_liability_plots: 0
plot_seq_logos: false
design_dir: /hai/scratch/fangwu97/workspace/workspace/prounderjoe/boltzgen/BoltzGen_runs_unimomo/4qci_D_B_A/intermediate_designs_inverse_folded
outdir: /hai/scratch/fangwu97/workspace/workspace/prounderjoe/boltzgen/BoltzGen_runs_unimomo/4qci_D_B_A
filter_designfolding: true
filter_biased: true
